import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import '../globals.css';

import React, { ReactNode } from 'react';

import { defaultLocale, isValidLocale } from '@/i18n/config';
import ClientI18nProvider from '@/shared/providers/lingui-provider/lingui-provider';
import { Footer, Header } from '@/widgets';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
  params: {
    lang: string;
  };
};

export default async function RootLayout({ children, params }: Props) {
  const locale = isValidLocale(params.lang) ? params.lang : defaultLocale;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <ClientI18nProvider locale={locale}>{children}</ClientI18nProvider>
        <Footer />
      </body>
    </html>
  );
}
